sudo: false
language: python
python: 3.5
install: pip install tox
script: tox
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7-dev
    env: TOXENV=py37
  - python: pypy3
    env: TOXENV=pypy3
notifications:
  email: false
deploy:
  provider: pypi
  user: mdowds
  password:
    secure: "j6ua8rNTgFqhnJpxsMugmm5yr8aQnxNlMr+6RnA9CP8bF7v08JKSzySKasd3qOBI0h9HIhsclHyFmDkOmkas+ZVaKNu07tNZCe12+RTwWDy8i3iAvyWQns/TfGO1e1DJ7maZbGkefU2dveoKfNNETibb7T1NoIBdNHlBIjrCGOcWF2K4lmquIz8hxVsrG2USjbr9vSf6jFObBucOt1pW+NueQVXURB5PzPkEwKvoIXg5m6bSxiOwPXOpz7R0HaklytS3WVvx4DM+pMZX32P0frdI+BAk2BRBZ82apkSncUk5eFUfRCHx0pikAapf6KxN4XxkHMFVhS6rGQGb41hf/3/7akKXiuTE/Rxm8kL+HYUDS3nCoLerA3DLJbbQJSGpKgH9R8kku9ve/8os7mDMT1VaDepAZhDftYeZCTZER8NloTQi0qA7VF0l86Dh+JDZT42MnOurcbRLHfWrn5GVQKWij3QrISI4CU6h3T0JIXGIHaFdjS4AcOkcLXSeeKKsdDns7FAFegjTZoHzY6AbWi5bzzmKMtZAqkys2XCObANmd6GwXR7c4VcmM5ltwg0aAjNempNHIsWK5QClYjxsTPZAED8QAGCnewkyDk/2WGbJqt34Jc+1saWOX4paZb/pUDoEnV4kk9xjCQ19iajbwlz5gYmhqtXMv9VUbquyrbo="
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
