sudo: false
language: python
python: 3.5
env:
- TOXENV=py35
install: pip install tox
script: tox
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7-dev
    env: TOXENV=py37
  - python: pypy3
    env: TOXENV=pypy3
notifications:
  email: false
deploy:
  provider: pypi
  user: mdowds
  password:
    secure: WrgkqaL1uyoS55cBYn5PbGP7liJrHAxsSxa7abbjAcrZpsQ2Ix5pDCU4jAtoBd3VWj98hGEBUiWxsnHUWNWwwCxgU3OJJ8Xk6xstlYu9F3sACa4/WpoYIGr8SKAYeJVyQ525eoamH0HMyQUG3iiFC1lSa4YBbFzpJglMPLRU1BQ4lXFjd2+P66jk8ok/Usy6la7c5QmwmIvatmLT7EOY1cRmlYcNzfEYmhSki32T9TL/2cI7LxC6FknsAFpeG+IbN/w2V35vsVsARwBWrCbgwhSrXkGSUZ0QeQpAlgTDnftjQx/StVMizsqYO7GF2dwwVIDxuEyMDtocPd7eATHVqEL9/3KI2yoBBn19wJM4DXCE1FzbeGrF974JMNbw758N1Bl1+KevXTrCPGJ/0U/8jSzGYnAcAIpW5UReniZdF46+46B5n92aKRtWGrXL9Lxthf45q/+xNyE8Fl4+3Gqyx25CKZNrYqbIC6a+yLFPEMNEiHAh+r/hzuNCZmdkT6xyfccbktu548QAxcTDIlZwhVSub2JAwe1pO6tFcHqE6Kw/20VKEjGoyselvcNqZtWWtzGbT7ZEXuTBYShJely/qr47e7JKnkOtOHkjShAqITHHMTWW2LO0t5+tPDbntRlJMec++Z/DQ4gHPrRnDunzAtaMjsnyIiOmC3KMUOWmNlI=
  on:
    branch: master
    tags: true
